// CREATE PRODUCT

POST http://localhost:3002/products
Content-Type: application/json

{
  "nama_barang": "New Product1",
  "foto_barang": "product.jpg",
  "harga_beli": 100,
  "harga_jual": 150,
  "stok": 10
}

###
// UPDATE PRODUCT

PATCH  http://localhost:3002/products/9
Content-Type: application/json

{
  "nama_barang": "New Product5",
  "foto_barang": "product.png",
  "harga_beli": 100,
  "harga_jual": 150,
  "stok": 10
}

###
// GET ALL PRODUCT

GET http://localhost:3002/products
Content-Type: application/json

###
// DELETE PRODUCT

DELETE http://localhost:3002/products/12

//------------------------------------------PRODUCT END

###
//CREATE USER
POST http://localhost:3002/users
Content-Type: application/json

{
    "name": "testadmin",
    "email": "admin@gmail.com",
    "password": "111111",
    "phone": "111111",
    "confPassword": "111111",
    "accountType": "Pegawai"
}


###
//FIND ALL USERS
GET http://localhost:3002/users
Content-Type: application/json

###
//FIND SPECIFIC USER
GET http://localhost:3002/users/1
Content-Type: application/json

###
//DESTROY USER
DELETE http://localhost:3002/users/7

###
//LOGIN USER ADMIN

POST http://localhost:3002/login
Content-Type: application/json

{
    "email": "febriandaru@gmail.com",
    "password": "111111"
}
###
//LOGIN USER CUSTOMER

POST http://localhost:3002/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "111111"
}

###
//ME
GET http://localhost:3002/me


###
//LOGOUT
DELETE http://localhost:3002/logout
